bug: 修复单张图片测试时label对应错误的问题
Fafa-DL/Awesome-Backbones pull request #51
Opened 2023-06-02 01:29 UTC by Psy-lzh

一个潜在小Bug，在使用图像分类程序时，如果annoations填写顺序反向的话，在测试时可能会输出错误
如：high为2在第一行，low为0但在第三行，就会在单张图片测试时出现label和class对不上的bug

本版本已修复上述bug，批量图片测试亦可参考本代码修改

2023-06-02 01:46 UTC, Fafa-DL requested changes
辛苦，merge前还需处理以下问题
1. 由于修改了inference函数，涉及到batch_test.py，video_test.py相应处未进行修改

2023-06-02 02:04 UTC, Psy-lzh commented
谢谢导师提醒，由于先前我主要使用single test，主要关注了单张图片的测试，后续其他函数我会尽快一起修改提交




祝工作顺利，平安喜乐！

刘子豪




--------------原始邮件--------------
发件人："Fafa&nbsp;Bro ***@***.***&gt;;
发送时间：2023年6月2日(星期五) 上午9:46
收件人："Fafa-DL/Awesome-Backbones" ***@***.***&gt;;
抄送："Psy-lzh ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [Fafa-DL/Awesome-Backbones] bug: 修复单张图片测试时label对应错误的问题 (PR #51)
-----------------------------------

 

 
@Fafa-DL requested changes on this pull request.
 
辛苦，merge前还需处理以下问题
  
由于修改了inference函数，涉及到batch_test.py，video_test.py相应处未进行修改
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-06-02 02:09 UTC, Fafa-DL commented
好的，涉及两行代码，修改内容和single_test相同，优先处理你的事，不急~

2023-06-08 02:15 UTC, Psy-lzh commented
导师好，batch_test.py，video_test.py对应部分已修改！再次夸夸，您这个代码写的很干净高效，学习起来很方便：）

2023-06-08 02:35 UTC, merged

2023-06-08 02:36 UTC, Fafa-DL commented
感谢，contributor里你可以看到自己啦~

2023-06-08 02:37 UTC, Psy-lzh commented
谢谢导师哈哈哈，希望以后还能和您有更多交流

----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："Fafa&nbsp;Bro ***@***.***&gt;;
发送时间：2023年6月8日(星期四) 上午10:36
收件人："Fafa-DL/Awesome-Backbones" ***@***.***&gt;;
抄送："Psy-lzh ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [Fafa-DL/Awesome-Backbones] bug: 修复单张图片测试时label对应错误的问题 (PR #51)
-----------------------------------

 

 
感谢，contributor里你可以看到自己啦~
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;